### ISSUE TITLE
renommer les dossiers

### ISSUE THREAD

**Issue by jorisSchaller** [ODAncona/pst_collab#2]
Les noms de dossier ne sont pas parlant.
On devrait avoir enoncer, corriger et source ou tex (par exemple)
mais destination, source et data. Sans aller voir le readme aucune idée d'où sont les corrigés

**Comment by AllemanoEn** [comment]
Oui effectivement. Quand on a mis ces noms avec @ODAncona c'était pour si retrouver avec TexStudio, nos fichiers sources et les destinations. Maintenant que plusieurs personnes vont utiliser le projet, des noms plus parlants seraient pluss adaptés !

**Comment by ODAncona** [comment]
J'ai renommé:
data -> enonces
dst -> corriges
